### ISSUE TITLE
ASSET PACK ERROR (V2)

### ISSUE THREAD

**Issue by pangwiny2** [Bambosh/unofficial-homestuck-collection#560] opened 2023-12-25 20:01 UTC
I INSTALLED THE UNOFFICIAL COLLECTION FROM THE GITHUB MIRROR AND THE ASSET PACK FROM MIRROR 1 TODAY;
I DIDN'T MAKE ANY MODIFICATIONS AND I EXTRACTED IT LIKE NORMAL. HOWEVER, IT SAYS I HAVE AN ERROR AND BELIEVES I HAVE V1. IT DIDN'T PREVIOUSLY WORK BEFORE I INSTALLED IT AND I DIDN'T MAKE ANY MODIFICATIONS, NOR DID I MOVE THE FOLDER.

ON STARTUP IT TAKES ME THROUGH THE PROCESS AS NORMAL, BUT WHEN IT ASKS ME TO LOCATE THE ASSETS, IT DOESN'T GIVE ME ANY ERRORS UNTIL I PRESS "ALL DONE, LET'S ROLL".
IT GIVES ME A SCREEN SHOWN IN THE SCREENSHOT; IF YOU PRESS "ALL DONE, LET'S ROLL" AGAIN, IT CRASHES/REOPENS THE APP AND GIVES ME THE STARTUP PROCESS AGAIN.

![image](https://github.com/Bambosh/unofficial-homestuck-collection/assets/64988653/7b390b1b-1cb7-4c56-a706-f62a172903d5)

**Desktop (please complete the following information):**
 - Program version: 2.4.1
 - Asset Pack Version: V2
 - OS: WINDOWS 11

![image](https://github.com/Bambosh/unofficial-homestuck-collection/assets/64988653/7b390b1b-1cb7-4c56-a706-f62a172903d5)

**Comment by mossball** [comment] 2023-12-31 22:45
I had the same problem, moving both the Asset Pack and The Program you mentioned to my D drive instead of my C drive worked.
Dunno why! But I had the exact same problem and doing this fixed the issue for me.

**Comment by OilFreak** [comment] 2024-01-03 16:35
I'm having the same issue on Mac. The app fails to access the asset pack, believing it to be missing. It doesn't even ask for desktop folder access.

**Comment by GiovanH** [comment] 2024-03-15 04:17
Duplicate of #563, fixed

**Closed by GiovanH** 2024-03-15 04:17 UTC
Labels: bug
