### ISSUE TITLE
Missing page 4815

### ISSUE THREAD

**Issue by LtooB** [Bambosh/unofficial-homestuck-collection#306] opened 2022-02-17 22:19 UTC
**Describe the bug**
Page 4815 doesn't load after asset update. For some reason the page name is DOTA.

**To Reproduce**
1. Go to page 4815
2. 

**Expected behavior**
I was supposed to see the page.

**Screenshots**
![The_Unofficial_Homestuck_Collection_esA8YgyJAu](https://user-images.githubusercontent.com/99924456/154580012-88f80416-d48f-4a53-8fbb-bc14a7b9b002.png) 
![The_Unofficial_Homestuck_Collection_jTdLVAxe1f](https://user-images.githubusercontent.com/99924456/154580025-e2522673-4e20-4e1c-8039-ff73154d496b.png)

**Desktop (please complete the following information):**
 - Program version: 2.0.4
 - Asset Pack Version: 2
 - OS: Windows 10

**Additional context**
This happened after I updated the assets from version 1 to version 2 and after replacing the program to the newest version.

**Comment by GiovanH** [comment] 2022-02-17 23:48
Duplicate of #293. Fixed in latest `develop`, fix will be in 2.0.5.

**Closed by GiovanH** 2022-02-17 23:48 UTC
Labels: bug
