### ISSUE TITLE
V2 assets aren't working

### ISSUE THREAD

**Issue by accountnamesdumb** [Bambosh/unofficial-homestuck-collection#542] opened 2023-09-15 18:32 UTC
- asset pack V2
 - The-Unofficial-Homestuck-Collection-2.4.1-win-x64
 - OS: windows10

When I finish with all the setup stuff (like the content warning, new readers) it says I'm not using the V2 asset pack but I am, I've tried redownloading the assets and even the app itself but it still doesn't work.

**Comment by minozomi** [comment] 2023-09-20 20:03
i have the same issue

**Comment by Derpentime** [comment] 2023-10-17 14:32
Same here. Commenting in hopes it will get fixed because this is incredibly frustrating. I have redownloaded it multiple times, and not to mention, I'm not the most tech savvy individual. I made it to a part in Homestuck where I quite literally need the flash functionality to move forward, and every time I try to open the collection, it just pretends like the v2 assets don't exist. I don't know what it is. I really hope it gets fixed soon.
![image_2023-10-17_073154800](https://github.com/Bambosh/unofficial-homestuck-collection/assets/148247234/f2345298-805f-4eaa-a2f0-69daf6b60060)

Before, I kept it in my harddrive along with where the actual collection was, and that didn't work. I tried moving it to the documents, and that didn't work either.

**Comment by loic-p** [comment] 2023-10-24 00:58
Same issue here. 
The asset pack is properly unzipped (with some header error, but I assume this is expected?), and the app complains that archive/data/version.json does not exist.

**Comment by KyleNicholUK** [comment] 2023-10-24 16:31
I have this same issue with the 32-bit version.

**Comment by KN-UK** [comment] 2023-10-24 16:35
I get this same issue - unzipped too.

**Comment by pangwiny2** [comment] 2023-12-25 19:38
I HAVE THIS PROBLEM TOO </3

**Comment by GiovanH** [comment] 2024-03-15 04:16
Duplicate of #563, fixed

**Closed by GiovanH** 2024-03-15 04:16 UTC
Labels: bug
