### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shacharaz** [Bambosh/unofficial-homestuck-collection#454] opened 2022-12-23 10:41 UTC
![image](https://user-images.githubusercontent.com/121291402/209321928-7817d577-672d-44a0-98f1-d5eb2579f48f.png)
This error message popped up when I attempted opening the app

**Comment by GiovanH** [comment] 2022-12-24 00:41
Duplicate of https://github.com/Bambosh/unofficial-homestuck-collection/issues/381. The workaround has already been posted and is available in releases.

**Closed by GiovanH** 2022-12-24 00:41 UTC
Labels: bug
