### ISSUE TITLE
Cannot run the program

### ISSUE THREAD

**Issue by SandaruKasa** [Bambosh/unofficial-homestuck-collection#401] opened 2022-06-24 13:08 UTC
**Describe the bug**
Cannot run the program. Tried building from source using AUR, running a pre-built binary both from AUR and from the website, and running the AppImage. 

**Tracebacks**
[Running a version built from AUR](https://github.com/Bambosh/unofficial-homestuck-collection/files/8976353/01_AUR.txt)
[Running a binary from AUR](https://github.com/Bambosh/unofficial-homestuck-collection/files/8976354/02_AUR_bin.txt)
[Running a binary from a .tar.gz archive from the website](https://github.com/Bambosh/unofficial-homestuck-collection/files/8976355/03_website_tar_gz.txt)
[Running AppImage from the website](https://github.com/Bambosh/unofficial-homestuck-collection/files/8976356/04_website_Appimage.txt)

**Desktop**
 - Program version: 2.0.5
 - Asset Pack Version: None
 - OS: Manjaro Linux x86_64 
 - Kernel: 5.18.5-1-MANJARO 
 - DE: Plasma 5.24.5

**Comment by GiovanH** [comment] 2022-06-27 04:01
Your problem is that last line, 
`15:31:53.811 (Mods)         › Got window
[286871:0624/153153.960316:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
fish: Job 1, './unofficial-homestuck-collecti…' terminated by signal SIGTRAP (Trace or breakpoint trap)`

**Comment by SandaruKasa** [comment] 2022-06-27 17:50
> Your problem is that last line
Oh, and how do I get rid of it?

**Comment by ioletsgo** [comment] 2022-06-29 21:01
ditto issue here

**Comment by perivance** [comment] 2022-07-10 14:23
Same problem on Arch, but I stumbled onto a workaround.
Run it in a terminal for the first time like this:
```
unofficial-homestuck-collection --in-process-gpu
```
It should go through the setup screen.
Once you finish that, you can run it as normal afterwards.

**Comment by GiovanH** [comment] 2022-07-30 01:46
Closing as a duplicate of #413

**Closed by GiovanH** 2022-07-30 01:46 UTC
Labels: bug
