### ISSUE TITLE
Workaround for "sharp" module error (unofficial)

### ISSUE THREAD

**Issue by DaRanMan** [Bambosh/unofficial-homestuck-collection#384] opened 2022-04-27 14:58 UTC
It appears several people have been encountering an error where the "sharp" module can't be installed. What fixed it for me was running version 1.1.0 before using the collection.

What to do:
1. Download, extract and run version 1.1.0 of the app. You can get it from [here](https://bambosh.github.io/unofficial-homestuck-collection/old_versions.html).
2. Close version 1.1.0 and delete it.
3. If you don't already have the latest versions of the app and asset pack, download and extract them from the website.
4. Launch the app normally and follow the in-app instructions.

It seems version 2 of the app can't install the "sharp" module; however, version 1 can, which lets version 2 launch properly.

**Comment by mimibluh** [comment] 2022-04-27 22:18
Tried it around twice, with no change to the newest version. Are there any other specific steps I might've missed?

**Comment by GiovanH** [comment] 2022-05-01 21:24
Closing as duplicate of https://github.com/Bambosh/unofficial-homestuck-collection/issues/381

(This is still a known problem, but we'll track it in one place. )

**Closed by GiovanH** 2022-05-01 21:24 UTC
