### ISSUE TITLE
Error occurs and won't launch

### ISSUE THREAD

**Issue by Tux9001** [Bambosh/unofficial-homestuck-collection#286] opened 2022-02-15 02:42 UTC
**Describe the bug**
When I try to open the program on Windows 10, an error occurs and I cannot continue.

**To Reproduce**
1. Download version 2.0.4 of the program for Windows.
2. Extract and run it.

**Expected behavior**
It opens up and works perfectly fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/34108937/153982295-0ab56880-1fef-4a39-953f-46f98483b550.png)

**Desktop (please complete the following information):**
 - V2.0.4
 - Asset Pack V2
 - OS: Windows 10

**Additional context**
The previous version worked completely fine, but the new version doesn't.

**Comment by GiovanH** [comment] 2022-02-15 05:54
Duplicate of #274. Please follow the instructions in the release notes, under Known Issue.

**Closed by GiovanH** 2022-02-15 05:54 UTC
Labels: bug
