### ISSUE TITLE
"A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by virgofilth** [Bambosh/unofficial-homestuck-collection#377] opened 2022-04-14 20:28 UTC
I have installed the asset pack, and have attempted both the 32-bit and 64-bit windows download, when I attempt to launch the collection I am met with the JavaScript error message - I've included a screenshot.

I know next to nothing about coding or JavaScript or computers in general, so any help given needs to be explained to me like I am 5 years old.

Thanks in advance!! 

![xx](https://user-images.githubusercontent.com/103689175/163470191-97d61817-2f39-4b1d-8cf9-52e36c198dde.PNG)

**Comment by mimibluh** [comment] 2022-04-17 21:59
I'm having the same problem, lol.

**Comment by DaRanMan** [comment] 2022-04-27 14:43
I had the same problem, too. What fixed it for me was running version 1.1.0 before using the collection.

What to do:
1. Download, extract and run version 1.1.0 of the app. You can get it from [here](https://bambosh.github.io/unofficial-homestuck-collection/old_versions.html).
2. Close version 1.1.0 and delete it.
3. If you don't already have the latest versions of the app and asset pack, download and extract them from the website.
4. Launch the app normally and follow the in-app instructions.

It seems version 2 of the app can't install the "sharp" module; however, version 1 can, which lets version 2 launch properly.

**Comment by GiovanH** [comment] 2022-05-01 21:23
Closing as duplicate of https://github.com/Bambosh/unofficial-homestuck-collection/issues/350

(This is still a known problem, but we'll track it in one place. )

**Closed by GiovanH** 2022-05-01 21:23 UTC
Labels: bug
