### ISSUE TITLE
Asset Pack V2 .zip Issue

### ISSUE THREAD

**Issue by LunaFeijoo97** [Bambosh/unofficial-homestuck-collection#514] opened 2023-06-28 13:20 UTC
Upon downloading the Asset Pack V2 .zip file with the torrent link, it seems that the .zip is corrupted. I'm trying to unzip it but it just throws "Corrupted File".

This error shows on a Linux machine running Ubuntu 23.04 Lunar. I'm using the native unzip method for Linux plus Terminal unzip one with no positive results. 

Thank you.

**Comment by thecnoNSMB** [comment] 2023-06-28 21:47
Use something like 7zip; the asset pack zip is too large for `unzip` to correctly handle.

**Comment by MolassesLover** [comment] 2023-06-30 11:57
Like @thecnoNSMB said, you need 7zip to extract the file. In my case, this command worked:
```sh
➜ 7z e Asset\ Pack\ V2\ -\ The\ Unofficial\ Homestuck\ Collection.zip
```

**Comment by noirscape** [comment] 2023-07-03 09:51
Duplicate of #353, see solution there.

**Closed** 2023-07-19 00:04 UTC
Labels: bug
