### ISSUE TITLE
Error message when starting the Unofficial Homestuck Collection. Please help <3

### ISSUE THREAD

**Issue by lizzie-wilton** [Bambosh/unofficial-homestuck-collection#358] opened 2022-03-20 14:51 UTC
I'm getting this error message when trying to use the .exe file. I've checked and the specified file is there. Please let me know what I can do as I really want to start reading Homestuck <3

https://i.ibb.co/Db76wz7/1.png
https://i.ibb.co/9vGQfYs/2.png
https://i.ibb.co/rG3wWrw/3.png

**Comment by lizzie-wilton** [comment] 2022-03-22 09:08
If anyone knows what my issue may be, please do let me know. I'm eager to start reading Homestuck and this is the only reasonable way to do it.

**Comment by lizzie-wilton** [comment] 2022-03-23 10:18
@GiovanH You asked me on Twitter to post my issue here. Any help would be appreciated :)

**Comment by VincentKnightTesting** [comment] 2022-04-08 18:07
~/.config/unofficial-homestuck-collection/config.json

manually edit this for the asset path, that's where the plugin is

**Comment by lizzie-wilton** [comment] 2022-04-10 17:03
> ~/.config/unofficial-homestuck-collection/config.json
> 
> manually edit this for the asset path, that's where the plugin is

Thank you, but I'm still not really sure what to do. Please could you give me a more detailed explination?

**Comment by lizzie-wilton** [comment] 2022-04-14 10:48
I'm still not sure what to do. Any assistance would be appreciated.

**Comment by abt-mortality** [comment] 2022-04-18 06:46
I’m having the same issue. If u figure anything out lmk :3

**Comment by VincentKnightTesting** [comment] 2022-04-18 11:31
> I'm still not sure what to do. Any assistance would be appreciated.

Sorry my previous comment was for a different issue. For this, the sharp module is in the app.asar.unpacked, try unpacking the app.asar again and seeing if the module is there? If not, try adding the module from app.asar.unpacked. Then recompile the file. This can all be done from the asar tool which (i think) can be installed with 'npm -i -g asar'

**Comment by abt-mortality** [comment] 2022-04-20 07:22
Thank you! I will try this :)

**Comment by GiovanH** [comment] 2022-05-01 21:13
Closing as duplicate of #381

(This is still a known problem, but we'll track it in one place. )

**Closed by GiovanH** 2022-05-01 21:13 UTC
Labels: bug
