### ISSUE TITLE
Sharp Module

### ISSUE THREAD

**Issue by pixzelia** [Bambosh/unofficial-homestuck-collection#388] opened 2022-05-17 17:39 UTC
Whenever I try to open the application I get an error message stating that something went wrong with installing the sharp module. I've downloaded it multiple times to the same result so it's not something going wrong on my end. I'm on windows.

**Comment by GiovanH** [comment] 2022-06-24 05:30
Duplicate of https://github.com/Bambosh/unofficial-homestuck-collection/issues/381 in the pinned issues.

**Closed by GiovanH** 2022-06-24 05:30 UTC
Labels: bug
