### ISSUE TITLE
plugin failing to load

### ISSUE THREAD

**Issue by Homestucker413** [Bambosh/unofficial-homestuck-collection#376] opened 2022-04-13 22:58 UTC
**Describe the bug**
Whenever i try to load a page in the unofficial homestuck collection that uses flash, the flash content is replaced with the "Couldn't Load Plugin" error.

**To Reproduce**
1. Go to any page in the app that uses flash (an example would be 253 of homestuck)
2. wait for it to load.
3. See error

**Expected behavior**
for page 253 of homestuck i expected the interactable flash page "[S] YOU THERE. BOY" to load.

**Screenshots**
![image](https://user-images.githubusercontent.com/103610713/163283194-6ec1cdaa-f7d9-4473-a6fa-636f518915da.png)

**Desktop (please complete the following information):**
 - Program version: 2.05
 - Asset Pack Version: V2
 - OS: Windows

**Comment by GiovanH** [comment] 2022-05-01 21:23
Closing as duplicate of https://github.com/Bambosh/unofficial-homestuck-collection/issues/381

(This is still a known problem, but we'll track it in one place. )

**Closed by GiovanH** 2022-05-01 21:23 UTC
Labels: bug
