### ISSUE TITLE
Can't open the app after updating!

### ISSUE THREAD

**Issue by notacomputerperson** [Bambosh/unofficial-homestuck-collection#284] opened 2022-02-14 23:53 UTC
Hi there! 
I am NOT proficient with computers at all and I think I messed something up when updating to 2.0. I am desperate for assistance, can anyone tell me how to fix this error? What did I do to prevent the app from opening??? Any and all help is deeply appreciated. Thank you :-)

![image](https://user-images.githubusercontent.com/99696727/153966437-bde1d222-8113-436e-8eda-abb801062698.png)

**Comment by GiovanH** [comment] 2022-02-14 23:54
Duplicate of #274

**Closed by GiovanH** 2022-02-14 23:54 UTC
