### ISSUE TITLE
App doesn't start when transferring data from old mac and the asset pack can't be located (resolved)

### ISSUE THREAD

**Issue by Red-Rax** [Bambosh/unofficial-homestuck-collection#278] opened 2022-02-14 17:38 UTC
I recently got a new macbook, and transferred all my data from my old macbook.  On my old macbook, I had the asset pack in an external harddrive, which I don't have connected to my new macbook.  Today, i updated my copy of the Unofficial Homestuck Collection, but when I went to open the app, I got an error message saying that the app couldn't find my external harddrive (because it wasn't attached), and it wouldn't let me start at all.  I was able to resolve the issue by going into [User]->Library->Application Support and deleting the entire "unofficial-homestuck-collection" folder, but i'm reporting the bug here for posterity.

**Comment by GiovanH** [comment] 2022-02-15 00:18
Duplicate of #274

**Closed by GiovanH** 2022-02-15 00:18 UTC
Labels: bug
