### ISSUE TITLE
Archival reader mode

### ISSUE THREAD

**Issue by shacharaz** [Bambosh/unofficial-homestuck-collection#474] opened 2023-02-22 06:56 UTC
When using the archival reader mode, page 5950 of Homestuck wrongly uses the retconned image
![image](https://user-images.githubusercontent.com/121291402/220545485-30387115-1b36-443a-b20c-40aed5d4a0b0.png)

**Comment by thecnoNSMB** [comment] 2023-02-22 08:20
Archival mode, in presenting the pages "approximately as they were at the time they were finished (or abandoned)", intentionally shows the "retcon" versions of Homestuck panels and flashes to new readers. If you do not wish those to be shown before the relevant story beat, please select Replay mode.

(I would close the issue as intended behavior but I'm not a maintainer -- if a maintainer comes across this issue, feel free to do so.)

**Comment by GiovanH** [comment] 2023-02-28 15:25
I believe this is correct; Archival mode should show the retconned versions of panels unless otherwise manually specified. The behaviour you're describing would be replay mode.

**Closed by GiovanH** 2023-02-28 15:25 UTC
Labels: bug
