### ISSUE TITLE
"Couldn't load plugin"

### ISSUE THREAD

**Issue by green-cmyk** [Bambosh/unofficial-homestuck-collection#371] opened 2022-04-06 18:54 UTC
**Describe the bug**
On every page with a plugin, an error message is shown that says "Couldn't load plugin".

**To Reproduce**
1. Go to any page with a plugin (such as /homestuck/250).
2. See error.
3. 
**Expected behavior**
I expect to be able to play/use the plugin.

**Screenshots**
![Screenshot 2022-04-06 135033](https://user-images.githubusercontent.com/103014791/162047371-c30b1741-7ed3-4678-b65a-644db0ab8ec9.png)

**Desktop (please complete the following information):**
 - Program version: v2.0.5
 - Asset Pack Version: v2
 - OS: Windows 32-bit

**Additional context**
I have tried relocating my assets and reinstalling both the assets and application.

**Comment by mataborg** [comment] 2022-04-10 14:59
Having the same issue on 64-bit, attached is the relevant log section:
```
[2022-04-10 15:56:03.011] [info] (page)                Found no audio for /storyfiles/hs2/00031/00031.swf undefined
[2022-04-10 15:56:03.012] [info] (page)                /homestuck/31 - John: Examine games on CD rack.
[2022-04-10 15:56:03.015] [info] (MediaEmbed)          Getting flash props for 00031 /storyfiles/hs2/00031/00031.swf
[2022-04-10 15:56:04.071] [info] (page)                /homestuck/30 - John: Forget it. Check mail later.
[2022-04-10 15:56:08.889] [info] (page)                Found no audio for /storyfiles/hs2/00031/00031.swf undefined
[2022-04-10 15:56:08.889] [info] (page)                /homestuck/31 - John: Examine games on CD rack.
[2022-04-10 15:56:08.890] [info] (MediaEmbed)          Getting flash props for 00031 /storyfiles/hs2/00031/00031.swf
[2022-04-10 15:56:10.328] [info] (page)                /homestuck/32 - John: Read COLONEL SASSACRE'S DAUNTING TEXT.
[2022-04-10 15:56:11.689] [info] (page)                Found no audio for /storyfiles/hs2/00031/00031.swf undefined
[2022-04-10 15:56:11.689] [info] (page)                /homestuck/31 - John: Examine games on CD rack.
[2022-04-10 15:56:11.690] [info] (MediaEmbed)          Getting flash props for 00031 /storyfiles/hs2/00031/00031.swf
```

**Comment by GiovanH** [comment] 2022-05-01 21:21
Closing as duplicate of https://github.com/Bambosh/unofficial-homestuck-collection/issues/350

(This is still a known problem, but we'll track it in one place. )

**Closed by GiovanH** 2022-05-01 21:21 UTC
Labels: bug
