### ISSUE TITLE
weird bug in windows edition

### ISSUE THREAD

**Issue by nope1game** [Bambosh/unofficial-homestuck-collection#399] opened 2022-06-23 15:07 UTC
This bug is a java script error and won't let me open the appilcation or flat out delete it.

i am on the windows edition of this software.

Here's the error message when I try to open it
![IMG_20220623_142622945](https://user-images.githubusercontent.com/108080653/175369422-a820b5bb-ef08-4934-ad50-96f09c7a7eb0.jpg)

Here's the error message when I try to delete it:
![IMG_20220623_142651034](https://user-images.githubusercontent.com/108080653/175369560-7a4f525b-c623-43cf-9a55-ba8b8e32a49c.jpg)

**Comment by GiovanH** [comment] 2022-06-24 05:30
Duplicate of https://github.com/Bambosh/unofficial-homestuck-collection/issues/381

**Closed by GiovanH** 2022-06-24 05:30 UTC
Labels: bug
