### ISSUE TITLE
Main app won't open

### ISSUE THREAD

**Issue by mimibluh** [Bambosh/unofficial-homestuck-collection#378] opened 2022-04-17 03:23 UTC
**Describe the bug**
When I attempt to open the main application for the collection (64), it pops up with a error message saying something went wrong with the "sharp" module. 

**To Reproduce**
1. Downloaded both the zipped asset pack folder and the folder for the main application.
2. Unzipped them both.
3. I go to the collection folder, and click on the main app.
4. See error.

**Expected behavior**
For the app to open regularly.

**Screenshots**
![Screenshot 2022-04-16 231909](https://user-images.githubusercontent.com/103868510/163698855-e35faa75-dabc-4b32-b465-701598c24274.png)

**Desktop (please complete the following information):**
 - Program 64bit version 2.0.5
 - Asset Pack Version V2
 - OS: Windows 11

**Additional context**
I previously had the 32bit version, which opened regularly, but wouldn't load plugins/flashes.
I'm not very smart when it comes to file stuff, so I don't know if this is even a problem related to the app. I do not know what the heck a sharp module is.

**Comment by abt-mortality** [comment] 2022-04-18 06:42
I have been having the exact same error! I asked on the official discord and searched the internet as well as I could but I have no idea how to fix this. Sorry for unhelpful comment I just wanted to let you know I’ve been getting the same javascript error.

**Comment by GiovanH** [comment] 2022-05-01 21:24
Closing as duplicate of https://github.com/Bambosh/unofficial-homestuck-collection/issues/381

(This is still a known problem, but we'll track it in one place. )

**Closed by GiovanH** 2022-05-01 21:24 UTC
Labels: bug
