### ISSUE TITLE
Command text cut off in [S] YOU THERE. BOY. - Page 253

### ISSUE THREAD

**Issue by JohnGM12** [Bambosh/unofficial-homestuck-collection#157] opened 2021-07-29 04:31 UTC
I'm running on Windows 10 with the V1.1.0 of the app, while exploring the flash I can click on the command text but parts of it will be cut off, such as "> THIS LARGE PLATFORM. GOOD GRIEF, WHAT IS IT BOY?" will end right at the O. I've tried moving John around to see if its just the screen cutting it off but the command box itself seems to just abruptly end. It's also not only this one that it happens on, pretty much any command box after a certain point gets cut off. Not only this but also a little bit later I found that going in and out of trickster mode with CTRL + T seems to freeze the app when I exit it, I need to manually close it and reopen it after. I went to another flash and it seems the problem persists but it has its command edge now.
![BOI](https://user-images.githubusercontent.com/7390617/127431730-44e6b78e-e991-438b-8afb-76d7cdf0a234.PNG)
![ext cut off](https://user-images.githubusercontent.com/7390617/127602160-edd95dc9-77a4-4440-afd0-392f6c44c09b.PNG)

**Comment by GiovanH** [comment] 2021-08-03 03:22
Can't reproduce. Are you using an abnormal DPI setting?

**Comment by JohnGM12** [comment] 2021-08-03 09:34
I don't believe so, my mouse comes with four dpi options through a button and after you asked this I tried all of them, they all seem to have the same issue

**Comment by GiovanH** [comment] 2021-08-03 23:09
DPI of the screen, not the mouse input

**Comment by JohnGM12** [comment] 2021-08-04 00:28
Oh, then no it shouldn't be abnormal because I haven't changed any screen dpi settings

**Comment by Bambosh** [comment] 2021-08-15 16:48
This is due to a change in DPI scaling over the years - the flash calculates the textbox width using character width, which behaves a little different nowadays. I tweaked this a while ago to alleviate the issue, so this should be resolved with the next release.

**Closed** 2021-08-15 16:49 UTC
Labels: question
