### ISSUE TITLE
flash pages.....

### ISSUE THREAD

**Issue by Metal228** [Bambosh/unofficial-homestuck-collection#503] opened 2023-05-09 14:18 UTC
Downloaded the homestuck collection, after running it successfully with assets and all, the flash pages say "couldnt load plugin"...??
wanted to get the full homestuck experience without the shitty youtube embedded on the homestuck website, and after downloading the homestuck collection it gives me a "couldnt load plug in" error image for all the flash animation pages! what can i do to fix this?? is this just a weird bug in the client?
my pc:
CPU: Intel(R) Celeron(R) CPU B800 @ 1.50GHz   1.50 GHz
system type: 32-bit operating system, x64 processor
release: Windows 10 Pro

**Comment by GiovanH** [comment] 2023-05-13 07:27
Duplicate of #459. Don't spam the issues page, and don't delete the issue template.

**Closed by GiovanH** 2023-05-13 07:27 UTC
