### ISSUE TITLE
The Homestuck Collection will not open on Mac

### ISSUE THREAD

**Issue by Crankers5G** [Bambosh/unofficial-homestuck-collection#287] opened 2022-02-15 08:59 UTC
**Describe the bug**

**To Reproduce**
1. Try to Open The Homestuck Collection.
3. Will Not Open.

**Expected behavior**
The Homestuck collection would open up.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
![Screen Shot 2022-02-15 at 12 51 12 AM](https://user-images.githubusercontent.com/99720210/154027309-59c619e3-b70e-468d-9150-900ff623d780.png)

**Desktop (please complete the following information):**
 - Program version: 2.04
 - Asset Pack Version: V2
 - OS: MacOS Monterey Version 12.1

**Additional context**

**Comment by thecnoNSMB** [comment] 2022-02-15 12:13
Duplicate of #274

**Closed** 2022-02-16 02:57 UTC
Labels: bug
